### PR TITLE
Add Tableau and Power BI Comparison

### PR DESCRIPTION
**Pull request by d33bs**
Adding content surrounding the comparison of Tableau and Power BI. My focus was to try and be as non-biased as I could while targeting only these two tools as asked. I found that, as far as what's advertised, there is a lot of technical parity between these tools and their platforms (besides Windows-only compatibility with Power BI Desktop). I tried to present major areas of non-technical information with links per tool in dedicated sections.

My impression is that it matters much more how these tools will be supported (both by internal resources as well as technical support for the platforms themselves) and who will be implementing the visualizations (both now and in the future). I tried to highlight this concern within the key questions section.

In case it's helpful for this or future conversations, I also added an alternatives section that includes two other large software competitors to Tableau and Power BI: Google Looker Studio and Apache Superset.

Aside: `dendron.yml` was also modified to account for Github organization name changes which have occurred since the last time this repository was edited.

### CODE REVIEW

**Comment by seandavi** [comment]
Just a note that Google Data Studio is now Looker Studio, a nod to the merger between Data Studio and Looker. https://cloud.google.com/looker-studio

**Comment by d33bs** [comment]
Thank you @seandavi! I'll make some updates to this effect.

**Review by vincerubinetti — APPROVED** [review]
FYI I've found that I don't have much insight into this. Consider this a token approval.

**Review by falquaddoomi — APPROVED** [review]
Nice work! I don't see any reason for this not be merged.

**Pull request merged**
